Repository Dokkabei97/dastargram, pull requests merged in 2023-06, with the labels that each got.

#3 인프라 구성 풀 리퀘스트
  .github/pull_request_template.md
  .github/workflows/build.yml
  docker-compose.yml
Labels: 풀 리퀘스트, 인프라

#4 마스터 브랜치 최신화 풀 리퀘스트
  .github/pull_request_template.md
  .github/workflows/build.yml
  docker-compose.yml
Labels: 풀 리퀘스트, 인프라

#20 Feature/cicd
  .dockerignore
  .github/ISSUE_TEMPLATE/버그-.md
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Dockerfile
  shell/extract_version.sh
Labels: 풀 리퀘스트, 인프라

#22 [PR] Comment Entity PullReuset
  src/main/kotlin/com/d1t/dastargram/domain/comment/api/CommentController.kt
  src/main/kotlin/com/d1t/dastargram/domain/comment/domain/Comment.kt
  src/main/kotlin/com/d1t/dastargram/domain/comment/domain/CommentStore.kt
  src/main/kotlin/com/d1t/dastargram/domain/comment/infrastructure/CommentRepository.kt
  src/main/kotlin/com/d1t/dastargram/domain/comment/infrastructure/CommentStoreImpl.kt
  src/test/kotlin/com/d1t/dastargram/domain/comment/domain/CommentTest.kt
Labels: 풀 리퀘스트, 코드 리뷰, 개발

#21 [PR] Post Entity PullReuset
  build.gradle.kts
  src/main/kotlin/com/d1t/dastargram/domain/post/domain/Post.kt
  src/main/kotlin/com/d1t/dastargram/domain/post/domain/PostStore.kt
  src/main/kotlin/com/d1t/dastargram/domain/post/infrastructure/PostRepository.kt
  src/main/kotlin/com/d1t/dastargram/domain/post/infrastructure/PostStoreImpl.kt
  src/test/kotlin/com/d1t/dastargram/domain/post/PostTest.kt
Labels: 풀 리퀘스트, 코드 리뷰, 개발

#24 Feature/common response
  .github/workflows/deploy.yml
  apis/member.http
  scripts/extract_version.sh
  src/main/kotlin/com/d1t/dastargram/domain/comment/domain/Comment.kt
  src/main/kotlin/com/d1t/dastargram/domain/member/api/MemberController.kt
  src/main/kotlin/com/d1t/dastargram/domain/member/domain/Member.kt
  src/main/kotlin/com/d1t/dastargram/domain/member/domain/MemberReader.kt
  src/main/kotlin/com/d1t/dastargram/domain/member/domain/MemberService.kt
  src/main/kotlin/com/d1t/dastargram/domain/member/domain/MemberServiceImpl.kt
  src/main/kotlin/com/d1t/dastargram/domain/member/dto/MemberRequest.kt
  src/main/kotlin/com/d1t/dastargram/domain/member/dto/MemberResponse.kt
  src/main/kotlin/com/d1t/dastargram/domain/member/infrastructure/MemberReaderImpl.kt
  src/main/kotlin/com/d1t/dastargram/domain/member/infrastructure/MemberRepository.kt
  src/main/kotlin/com/d1t/dastargram/domain/post/domain/Post.kt
  src/main/kotlin/com/d1t/dastargram/global/common/entity/AbstractEntity.kt
  src/main/kotlin/com/d1t/dastargram/global/common/interceptor/CommonRequestInterceptor.kt
  src/main/kotlin/com/d1t/dastargram/global/common/response/CommonControllerAdvice.kt
  src/main/kotlin/com/d1t/dastargram/global/common/response/CommonResponse.kt
  src/main/kotlin/com/d1t/dastargram/global/common/response/ErrorCode.kt
  src/main/kotlin/com/d1t/dastargram/global/config/entity/JpaAuditingConfiguration.kt
  src/main/kotlin/com/d1t/dastargram/global/config/web/WebConfig.kt
  src/main/resources/application-dev.yml
  src/test/kotlin/com/d1t/dastargram/domain/member/api/MemberControllerTest.kt
  src/test/kotlin/com/d1t/dastargram/domain/member/domain/MemberServiceImplTest.kt
Labels: 풀 리퀘스트, 개발
